import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.kover)
    alias(libs.plugins.android.library)
}

// Make the generated `Res` class public so the desktopApp module can reach
// `Res.string.*` / `Res.array.*` accessors.
compose.resources {
    publicResClass = true
}

// Generates `dev/hackathon/linkopener/BuildVersion.kt` so that
// AppInfoRepositoryImpl (Settings sidebar) can read the same version that
// desktopApp/build.gradle.kts uses for DMG metadata. Single source of truth:
// `linkopener.version` in root gradle.properties.
//
// Resolve Providers at configuration time and capture only the flat
// String / File values in the doLast lambda — Gradle's configuration cache
// can't serialize Provider references that close over the script object.
val generateBuildVersion = tasks.register("generateBuildVersion") {
    val versionString: String = providers.gradleProperty("linkopener.version").get()
    val outputFile = layout.buildDirectory
        .file("generated/version/dev/hackathon/linkopener/BuildVersion.kt")
        .get().asFile
    inputs.property("version", versionString)
    outputs.file(outputFile)
    doLast {
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            """
            |// Generated by :shared:generateBuildVersion. Do not edit by hand —
            |// bump `linkopener.version` in root gradle.properties instead.
            |package dev.hackathon.linkopener
            |
            |internal const val APP_VERSION: String = "$versionString"
            |""".trimMargin()
        )
    }
}
val generatedVersionDir = layout.buildDirectory.dir("generated/version")

kotlin {
    jvm {
        compilerOptions { jvmTarget = JvmTarget.JVM_17 }
    }

    androidTarget {
        compilerOptions { jvmTarget = JvmTarget.JVM_17 }
        // Publish only the release variant — the debug variant pulls extra
        // overhead we don't need for a library consumed by :androidApp.
        publishLibraryVariants("release")
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generatedVersionDir)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.resources)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.multiplatformSettings)
                implementation(libs.reorderable)
            }
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }

        // Skia native runtime for the host OS — required by tests that
        // exercise PlatformImageDecoder.jvm. The multiplatform Compose deps
        // in commonMain only bring the API stubs; the actual libskiko-*
        // native lib comes from compose.desktop.currentOs.
        val jvmTest by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }

        // Robolectric — runs Android framework code (Intent, PackageManager,
        // ResolveInfo, etc.) on a host JVM by substituting "shadow" impls
        // for the stub-only android.jar. Without it, every Android test
        // would throw RuntimeException("Stub!") on first framework call.
        val androidUnitTest by getting {
            dependencies {
                implementation(libs.junit)
                implementation(libs.robolectric)
                // ApplicationProvider — provides a Robolectric-managed
                // Application instance to tests that need a Context.
                implementation(libs.androidx.test.core)
            }
        }

        jvmMain.dependencies {
            implementation(libs.kotlinx.coroutines.swing)
            // JNA — used on Windows to call shell32!SHChangeNotify after
            // registering as URL handler so the Default Apps cache flushes.
            // No-op load on macOS/Linux (we swallow the exception).
            implementation(libs.jna)
        }
    }
}

// Make every Kotlin compile pick up the freshly-generated BuildVersion.kt.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateBuildVersion)
}

// Stage 09 A2 — Android Gradle Plugin extension. The KMP plugin wires the
// `androidMain` source set automatically; we just need the basics here:
// namespace (mandatory since AGP 7.x), SDK levels, and source/target Java
// version to match the JVM target.
android {
    namespace = "dev.hackathon.linkopener.shared"
    compileSdk = 36
    defaultConfig {
        minSdk = 26
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    // Robolectric needs a real-ish Android resource graph + a target SDK
    // declaration to pick a runtime version. Without `isReturnDefaultValues`
    // any Android-stub call from non-Robolectric tests would throw; we
    // leave it false because Robolectric supplies real impls.
    testOptions {
        unitTests.isIncludeAndroidResources = true
    }
}

kover {
    reports {
        filters {
            excludes {
                // UI surface — exercised manually / by stage 4.5 design system, not unit-tested.
                // ComposableSingletons* are the synthetic Kt classes Compose's compiler
                // emits for `@Composable () -> Unit` lambdas captured from each screen.
                //
                // The ui.settings.{components,sections} packages were carved out of
                // SettingsScreen.kt during the round-1 refactor — same Compose-UI
                // category, same exclusion rationale.
                classes(
                    "dev.hackathon.linkopener.ui.icons.**",
                    "dev.hackathon.linkopener.ui.settings.SettingsScreen*",
                    "dev.hackathon.linkopener.ui.settings.NavSection*",
                    "dev.hackathon.linkopener.ui.settings.ComposableSingletons*",
                    "dev.hackathon.linkopener.ui.settings.components.**",
                    "dev.hackathon.linkopener.ui.settings.sections.**",
                    "dev.hackathon.linkopener.ui.picker.BrowserPickerScreen*",
                    "dev.hackathon.linkopener.ui.picker.ComposableSingletons*",
                    "dev.hackathon.linkopener.ui.strings.LocalAppLocaleKt*",
                    "dev.hackathon.linkopener.ui.strings.LocalizedLabelsKt*",
                    "dev.hackathon.linkopener.ui.theme.LinkOpenerTheme*",
                    "dev.hackathon.linkopener.ui.theme.LinkOpenerColors*",
                    "dev.hackathon.linkopener.ui.theme.LinkOpenerTypography*",
                    "dev.hackathon.linkopener.ui.theme.BrowserAvatar*",
                    "dev.hackathon.linkopener.ui.theme.SurfaceTones*",
                    "dev.hackathon.linkopener.ui.tray.**",
                )
                // Compose Resources generates accessor classes (`Res`, `String0_*`,
                // `Array0_*`, `ActualResourceCollectorsKt`) — they're build-time
                // generated, not authored.
                classes(
                    "kmp_link_opener.shared.generated.**",
                )
                // Process-spawning / framework-glue layers we'd only smoke-test on the
                // matching OS. The default-browser services on macOS / Windows shell out
                // via ProcessBuilder; the linux impl is a no-op stub and IS unit-tested.
                classes(
                    "dev.hackathon.linkopener.platform.JvmUrlReceiver*",
                    "dev.hackathon.linkopener.platform.macos.PlutilRunner*",
                    "dev.hackathon.linkopener.platform.macos.MacOsAutoStartManager*",
                    "dev.hackathon.linkopener.platform.macos.MacOsDefaultBrowserService*",
                    // Stage 7 Windows: WindowsDefaultBrowserService.openSystemSettings
                    // shells out (`cmd /c start ms-settings:defaultapps`) — same exclusion
                    // pattern as MacOsDefaultBrowserService. All registry-reading and
                    // argv-building logic IS unit-tested via captured fixtures.
                    "dev.hackathon.linkopener.platform.windows.WindowsDefaultBrowserService*",
                )
            }
        }
    }
}
