import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.kover)
}

// Make the generated `Res` class public so the desktopApp module can reach
// `Res.string.*` / `Res.array.*` accessors.
compose.resources {
    publicResClass = true
}

// Generates `dev/hackathon/linkopener/BuildVersion.kt` so that
// AppInfoRepositoryImpl (Settings sidebar) can read the same version that
// desktopApp/build.gradle.kts uses for DMG metadata. Single source of truth:
// `linkopener.version` in root gradle.properties.
//
// Resolve Providers at configuration time and capture only the flat
// String / File values in the doLast lambda — Gradle's configuration cache
// can't serialize Provider references that close over the script object.
val generateBuildVersion = tasks.register("generateBuildVersion") {
    val versionString: String = providers.gradleProperty("linkopener.version").get()
    val outputFile = layout.buildDirectory
        .file("generated/version/dev/hackathon/linkopener/BuildVersion.kt")
        .get().asFile
    inputs.property("version", versionString)
    outputs.file(outputFile)
    doLast {
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            """
            |// Generated by :shared:generateBuildVersion. Do not edit by hand —
            |// bump `linkopener.version` in root gradle.properties instead.
            |package dev.hackathon.linkopener
            |
            |internal const val APP_VERSION: String = "$versionString"
            |""".trimMargin()
        )
    }
}
val generatedVersionDir = layout.buildDirectory.dir("generated/version")

kotlin {
    jvm {
        compilerOptions { jvmTarget = JvmTarget.JVM_17 }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generatedVersionDir)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.resources)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.multiplatformSettings)
                implementation(libs.reorderable)
            }
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }

        jvmMain.dependencies {
            implementation(libs.kotlinx.coroutines.swing)
        }
    }
}

// Make every Kotlin compile pick up the freshly-generated BuildVersion.kt.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateBuildVersion)
}

kover {
    reports {
        filters {
            excludes {
                // UI surface — exercised manually / by stage 4.5 design system, not unit-tested.
                // ComposableSingletons* are the synthetic Kt classes Compose's compiler
                // emits for `@Composable () -> Unit` lambdas captured from each screen.
                //
                // The ui.settings.{components,sections} packages were carved out of
                // SettingsScreen.kt during the round-1 refactor — same Compose-UI
                // category, same exclusion rationale.
                classes(
                    "dev.hackathon.linkopener.ui.icons.**",
                    "dev.hackathon.linkopener.ui.settings.SettingsScreen*",
                    "dev.hackathon.linkopener.ui.settings.NavSection*",
                    "dev.hackathon.linkopener.ui.settings.ComposableSingletons*",
                    "dev.hackathon.linkopener.ui.settings.components.**",
                    "dev.hackathon.linkopener.ui.settings.sections.**",
                    "dev.hackathon.linkopener.ui.picker.BrowserPickerScreen*",
                    "dev.hackathon.linkopener.ui.picker.ComposableSingletons*",
                    "dev.hackathon.linkopener.ui.strings.LocalAppLocaleKt*",
                    "dev.hackathon.linkopener.ui.strings.LocalizedLabelsKt*",
                    "dev.hackathon.linkopener.ui.theme.LinkOpenerTheme*",
                    "dev.hackathon.linkopener.ui.theme.LinkOpenerColors*",
                    "dev.hackathon.linkopener.ui.theme.LinkOpenerTypography*",
                    "dev.hackathon.linkopener.ui.theme.BrowserAvatar*",
                    "dev.hackathon.linkopener.ui.theme.SurfaceTones*",
                    "dev.hackathon.linkopener.ui.tray.**",
                )
                // Compose Resources generates accessor classes (`Res`, `String0_*`,
                // `Array0_*`, `ActualResourceCollectorsKt`) — they're build-time
                // generated, not authored.
                classes(
                    "kmp_link_opener.shared.generated.**",
                )
                // Process-spawning / framework-glue layers we'd only smoke-test on the
                // matching OS. The default-browser services on macOS / Windows shell out
                // via ProcessBuilder; the linux impl is a no-op stub and IS unit-tested.
                classes(
                    "dev.hackathon.linkopener.platform.JvmUrlReceiver*",
                    "dev.hackathon.linkopener.platform.macos.PlutilRunner*",
                    "dev.hackathon.linkopener.platform.macos.MacOsAutoStartManager*",
                    "dev.hackathon.linkopener.platform.macos.MacOsDefaultBrowserService*",
                    "dev.hackathon.linkopener.platform.windows.WindowsDefaultBrowserService*",
                )
            }
        }
    }
}
